application: arquitetura-site
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static_files/index.htm
  upload: static_files/index.htm

- url: /
  static_dir: static_files
